### PR TITLE
1.0/333 guard production data routes

### PR DESCRIPTION
**Pull request by katjam**
@charlesstrange2 Can I keep my teapots? Can I?

:tea:

### CODE REVIEW

**Comment by katjam** [comment]
lol... I return 418 😄

**Comment by charlesstrange2** [comment]
Ah, yes, "I'm an Internet connected teapot"; I clocked the 4xx code and
thought, 'yup, looks like a specific error' but hadn't recalled the spec.

Keep it for the humour. ;)

**Comment by katjam** [comment]
Yay! You are super. Thanks... have a great swim.

**Comment by katjam** [comment]
I promise they will go when we build it for real.

**Pull request merged**
